name: "CI Checks"
on:
  workflow_dispatch:
  push:

jobs:
  run-ci:
    strategy:
      matrix:
        include:
          - runner: ubuntu-latest
            goos: linux
          - runner: macos-latest
            goos: darwin
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build CLI
        run: |
          make build
      - name: Run tests
        run: |
          make test
