name: "CI Checks"
on:
  workflow_dispatch:
  push:
  pull_request:

jobs:
  run-ci:
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build CLI
        run: |
          make build
      - name: Run tests
        run: |
          make test
